### ISSUE TITLE
Dokumentation bez. Bewegungsmelder

### ISSUE THREAD

**Issue by guggu1** [TA2k/ioBroker.mystrom#180]
Leider kann ich in der Doku nichts finden, was der Adapter für den Bewegungsmelder liefert.

Im Speziellen: 

- gibt es eine Meldung, z.B. in einem Objekt, wenn eine Bewegung beobachtet wird
- was geschieht, wenn während einer bestimmten Zeit KEINE Bewegung mehr beobachtet wird.

Ich finde zwar:

**PIR Bewegungsmelder
Unter Objekte folgenden State setzen mystrom.0.XXXXX.localData.api/v1/action.pir**

kann das aber nicht interpretieren.

Danke für eine Erläuterung

Christoph S

**Comment by TA2k** [comment]
Ich denke der status geht auch true oder false bei Bewegung

**Comment by guggu1** [comment]
Stimmt.
