### ISSUE TITLE
localUpdateInterval reset

### ISSUE THREAD

**Issue by guggu1** [TA2k/ioBroker.mystrom#181]
(for WifiSwitch) the localUpdateInterval (see object tree below, where the interval is set to 5 seconds) is reset to 60 seconds after an adapter (re)start.

Christoph S

![image](https://user-images.githubusercontent.com/23314447/212488135-919f16c1-989b-4c2d-9fa0-fc80aa22ae60.png)

**Comment by TA2k** [comment]
bitte GitHub version testen ob es gefixt ist

**Comment by guggu1** [comment]
ich habe V0.0.14 installiert und finde keine neuere Version.

![image](https://user-images.githubusercontent.com/23314447/212490167-49bbc905-777d-4f04-9ae7-1059a1bbca20.png)

**Comment by TA2k** [comment]
Im experten modus via GitHub Katze installieren version ist gleich

**Comment by guggu1** [comment]
gewusst wie! Danke. Es ist gelöst
