### ISSUE TITLE
Keine Daten vom Bewegungsmelder

### ISSUE THREAD

**Issue by guggu1** [TA2k/ioBroker.mystrom#182]
ich habe einen myStrom Bewegungsmelder "myStrom Motion" angeschlossen. Er wird vom Adapter erkannt.
Der Bewegungsmelder hat eine feste IP-Adresse im WLan.
Nach dem (neu) Start des Adapters, oder wenn ich "localUpdateInterval" ändere, erhält der Adapter "motion", "temperature" und "light" Daten. Nach einer gewissen Zeit werden die Werte aber in "localData" nicht mehr nachgeführt.

Zur Prüfung, ob der Bewegungsmelder funktioniert, habe ich ein Script entwickelt, welche die Daten periodisch über einen "Http Request" abfragt. Siehe Anhang. Es funktioniert zuverlässig.

Habe ich etwas übersehen bei der Einrichtung des Adapters?

Christoph S

[Blockly Script Bewegungsmelder.pdf](https://github.com/TA2k/ioBroker.mystrom/files/10527158/Blockly.Script.Bewegungsmelder.pdf)

**Comment by guggu1** [comment]
Nachtrag:

der einzige Log-Eintrag des Adapters ist:

mystrom.0 | 2023-01-28 13:06:56.235 | info | State value to set for "mystrom.0.FCF5C41A0218.cloudStatus.light" has to be stringified but received type "number"
-- | -- | -- | --
 

<br class="Apple-interchange-newline">

**Comment by TA2k** [comment]
Du kannst mal debug log level für die Instanz aktivieren und schauen wann und wie Daten kommen

**Comment by guggu1** [comment]
unten der log, direkt nach dem Start des Adapters. Anschliessen gibt es keine Einträge mehr, auch wenn der Sensor und mein Script Bewegungen erkennen.



strom.0 | 2023-01-28 17:32:05.648 | debug | {"rest":true,"panel":true,"hap_disable":false,"name":"","temp_offset":0}
-- | -- | -- | --
mystrom.0 | 2023-01-28 17:32:04.736 | debug | {"measured":42.12,"compensation":22.43,"compensated":19.68,"offset":0}
mystrom.0 | 2023-01-28 17:32:04.714 | debug | {"success":true,"motion":false}
mystrom.0 | 2023-01-28 17:32:04.703 | debug | {"success":true,"intensity":48,"day":true,"raw":{"adc0":48,"adc1":12}}
mystrom.0 | 2023-01-28 17:32:04.697 | debug | {"motion":false,"light":48,"temperature":19.68}
mystrom.0 | 2023-01-28 17:32:04.695 | debug | {"rest":true,"panel":true,"hap_disable":false,"name":"","temp_offset":0}
mystrom.0 | 2023-01-28 17:32:04.679 | debug | {"measured":40.56,"compensation":18.24,"compensated":22.31,"offset":0}
mystrom.0 | 2023-01-28 17:32:04.677 | debug | {"pir":{"generic":"","night":"","twilight":"","day":"","rise":"","fall":""}}
mystrom.0 | 2023-01-28 17:32:04.674 | debug | {"power":29.86,"Ws":30.12,"relay":true,"temperature":22.31}
mystrom.0 | 2023-01-28 17:32:04.616 | debug | Get: http://192.168.1.102/api/v1/settings
mystrom.0 | 2023-01-28 17:32:04.614 | debug | Get: http://192.168.1.102/temp
mystrom.0 | 2023-01-28 17:32:04.614 | debug | Get: http://192.168.1.102/report
mystrom.0 | 2023-01-28 17:32:04.613 | debug | {"id":"807D3A8A02FC","type":"ws2"}
mystrom.0 | 2023-01-28 17:32:04.592 | debug | Get: http://192.168.1.131/api/v1/settings
mystrom.0 | 2023-01-28 17:32:04.591 | debug | Get: http://192.168.1.131/temp
mystrom.0 | 2023-01-28 17:32:04.590 | debug | Get: http://192.168.1.131/api/v1/motion
mystrom.0 | 2023-01-28 17:32:04.587 | debug | Get: http://192.168.1.131/api/v1/light
mystrom.0 | 2023-01-28 17:32:04.586 | debug | Get: http://192.168.1.131/api/v1/sensors
mystrom.0 | 2023-01-28 17:32:04.582 | debug | Get: http://192.168.1.131/api/v1/action
mystrom.0 | 2023-01-28 17:32:04.580 | debug | {"id":"FCF5C41A0218","type":"pir"}
mystrom.0 | 2023-01-28 17:32:04.573 | debug | [{"id":"FCF5C41A0218","type":"pir"},{"id":"807D3A8A02FC","type":"ws2"}]
mystrom.0 | 2023-01-28 17:31:59.932 | debug | {"status":"ok","info":{"MAC":"807D3A8A02FC","Type":"WS2","IPv4":"192.168.1.102","SSID":"GugguSwisscom","Signal":"94","FW":"4.0.4"}}
mystrom.0 | 2023-01-28 17:31:59.823 | debug | {"status":"ok","settings":"{\"appVersion\":\"4.0.4\",\"dns2\":\"\",\"dns1\":\"192.168.1.1\",\"localSingleURL\":\"\",\"localTouchUrl\":\"\",\"isBridge\":\"false\",\"heartbeatPeriod\":\"60\",\"mac\":\"807D3A8A02FC\",\"serverPassword\":\"\",\"localDoubleUrl\":\"\",\"reportPeriod\":\"30\",\"wlanRssi\":\"94\",\"serverSsl\":\"true\",\"ipv4\":\"192.168.1.102\",\"wlanSsid\":\"GugguSwisscom\",\"kernelVersion\":\"4.1.0\",\"serverUrl\":\"device.mystrom.ch:443\",\"localLongUrl\":\"\",\"hardwareVersion\":\"1.0.0\",\"gateway\":\"192.168.1.1\",\"dhcpEnabled\":\"true\"}"}
mystrom.0 | 2023-01-28 17:31:59.801 | debug | {"status":"ok","settings":"{\"appVersion\":\"4.0.4\",\"dns2\":\"\",\"dns1\":\"192.168.1.1\",\"localSingleURL\":\"\",\"localTouchUrl\":\"\",\"isBridge\":\"false\",\"heartbeatPeriod\":\"60\",\"mac\":\"FCF5C41A0218\",\"serverPassword\":\"\",\"localDoubleUrl\":\"\",\"reportPeriod\":\"30\",\"wlanRssi\":\"98\",\"serverSsl\":\"true\",\"ipv4\":\"192.168.1.131\",\"wlanSsid\":\"GugguSwisscom\",\"kernelVersion\":\"4.1.0\",\"serverUrl\":\"device.mystrom.ch:443\",\"localLongUrl\":\"\",\"hardwareVersion\":\"1.0.0\",\"gateway\":\"192.168.1.1\",\"dhcpEnabled\":\"true\"}"}
mystrom.0 | 2023-01-28 17:31:59.698 | debug | {"status":"ok","info":{"MAC":"FCF5C41A0218","Type":"PIR","IPv4":"192.168.1.131","SSID":"GugguSwisscom","Signal":"98","FW":"4.0.4"}}
mystrom.0 | 2023-01-28 17:31:59.676 | info | State value to set for "mystrom.0.FCF5C41A0218.cloudStatus.light" has to be stringified but received type "number"
mystrom.0 | 2023-01-28 17:31:59.539 | debug | {"status":"ok","devices":[{"id":"FCF5C41A0218","name":"BewTV","type":"pir","state":"on","motion":"MOTION_END","light":48,"localIp":"192.168.1.131","deviceTypeId":"HotidOrc0OcVetFo","deviceTypeName":"PIR/Motion Detector 2","deviceTypeKey":"pir_2","powerColor":"#39b54a","power":0,"alerts":[{"type":"motion_night","enabled":true,"channels":["none"]},{"type":"motion_day","enabled":true,"channels":["none"]}],"schedule":{"enabled":false,"ranges":""},"energyReport":{"allCost":"0.00 CHF"},"currentFirmwareVersion":"4.0","fullFirmwareVersion":"4.0.4","newFirmwareAvailable":false,"wifiSwitchTemp":19.68,"time":"2023-01-28 16:31:46Z","dayLevel":100,"nightLevel":30,"releaseTime":30,"supportsWifiInfo":true,"firstDeviceRegistrationDate":"2023-01-18 16:15:32Z","homeKitTokenSet":true,"homeKitTokenSupported":true,"homeKitSetupCode":"971-92-496","homeKitSetupId":"D9M6","homeKitIsSavedOnDevice":true,"homeKitSavedOnDeviceDate":"2023-01-18 17:50:03.0","homeKitIsConfirmed":true,"homeKitConfirmedDate":"2023-01-18 17:50:03.0","room":{"id":"aD7lX0dVUbWXshWH","name":"Fernsehzimmer","type":"office","color":"#a1cbe1"}},{"id":"807D3A8A02FC","name":"TVSchalter","type":"ws2","state":"on","localIp":"192.168.1.102","deviceTypeId":"mgcSLEtmj6kDNvb2","deviceTypeName":"Switch/Adapter","deviceTypeKey":"switch_adapter","powerColor":"#39b54a","power":31.982386,"alerts":[{"type":"auto_off","enabled":false,"channels":["none"]},{"type":"timer","enabled":false,"channels":["none"],"action":false,"start":1674316493960,"period":60000},{"type":"standby","enabled":true,"channels":["none"]},{"type":"device_turned_off","enabled":true,"channels":["none"]}],"schedule":{"enabled":false,"ranges":""},"energyReport":{"allCost":"0.86 CHF"},"currentFirmwareVersion":"4.0","fullFirmwareVersion":"4.0.4","newFirmwareAvailable":false,"wifiSwitchTemp":22.31,"time":"2023-01-28 16:31:58Z","supportsTimer":true,"supportsWifiInfo":true,"firstDeviceRegistrationDate":"2018-11-23 14:41:30Z","homeKitTokenSet":true,"homeKitTokenSupported":true,"homeKitSetupCode":"254-33-656","homeKitSetupId":"QP83","homeKitIsSavedOnDevice":true,"homeKitSavedOnDeviceDate":"2021-11-13 09:06:40.0","homeKitIsConfirmed":true,"homeKitConfirmedDate":"2021-11-13 09:06:39.0","room":{"id":"aD7lX0dVUbWXshWH","name":"Fernsehzimmer","type":"office","color":"#a1cbe1"}}]}
mystrom.0 | 2023-01-28 17:31:59.340 | debug | {"status":"ok","authToken":"Ch7USI7bUMtu4rV5-sYiSbN5g7fi9AGm1","name":"Christoph Schifferli","fname":"Christoph","lname":"Schifferli","email":"chr.schifferli@bluewin.ch","accountType":"pro","currency":"CHF","onlineShop":"https://mystrom.ch/","appUrl":"https://mystrom.ch","termsAccepted":true,"timeZone":"Europe/Zurich","tariffPrice":"custom 0.33 CHF / 0.30 CHF","supportedDeviceTypes":{"sha":"full","pir":"full","lcs":"full","wrb":"full","gw":"full","bp2":"full","wbp":"full","dim":"full","wrs":"full","eth":"existing_only","wsw":"full","brg":"full","mst":"existing_only","ws2":"full","din":"full","sns":"full","wbs":"full","wll":"full","wse":"full"}}
mystrom.0 | 2023-01-28 17:31:58.965 | info | starting. Version 0.0.14 in /opt/iobroker/node_modules/iobroker.mystrom, node: v18.9.0, js-controller: 3.3.22
mystrom.0 | 2023-01-28 17:31:52.897 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
mystrom.0 | 2023-01-28 17:31:52.894 | info | terminating
mystrom.0 | 2023-01-28 17:31:52.893 | info | cleaned everything up...
mystrom.0 | 2023-01-28 17:31:52.888 | info | Got terminate signal TERMINATE_YOURSELF

**Comment by TA2k** [comment]
Ist mit der GitHub version gefixt

**Comment by guggu1** [comment]
Funktioniert. Danke
