### ISSUE TITLE
Error Log wird geflutet

### ISSUE THREAD

**Issue by jhartlep** [TA2k/ioBroker.mystrom#67]
Moin, ich bekomme bei installierter Version 0.0.5 im <1 Sekunden Takt ETIMEDOUT Fehler im Log.
Es wird in einem Affenzahl versucht, diverse Daten von /report, /temp, /api/v1/settings abzufragen.

Ich habe in den Instanzeinstellungen nichts gefunden, um das Abfrageintervall höher zu stellen.
Ich vermute mal, dass die API vom myStrom-Steckdosenadapter hier schlicht weg sperrt.
Denn der Adapter selbst zeigt im ioBroker korrekte Werte und ist auch korrekt verbunden.

Wie kann ich hier denn ein anderes Abfrageintervall einstellen?

**Comment by TA2k** [comment]
Ist das auch bei der github version so?

**Comment by jhartlep** [comment]
Moin,
habe gerade die github-Version (custom from URL) installiert. Ich gebe morgen früh ein Update, wenn ich dann wieder ins Log schaue. Aktuell scheint es gut auszusehen.

**Comment by jhartlep** [comment]
Jetzt sind es keine Errors mehr, sondern Warnings.
Ich bekomme also immer noch die ETIMEDOUT Meldungen.

**Comment by TA2k** [comment]
Du kannst die log level auf error setzen.
Ist das Gerät nicht erreichbar?

**Comment by jhartlep** [comment]
Doch, das Gerät ist erreichbar.

Die Abfragen werden halt nur extrem schnell abgefeuert (zumindest scheint es mir so).

`
mystrom.0 | 2021-08-20 10:00:54.681 | warn | Error: connect ETIMEDOUT 192.168.4.248:80
mystrom.0 | 2021-08-20 10:00:54.681 | warn | http://192.168.4.248/api/v1/settings
mystrom.0 | 2021-08-20 10:00:54.681 | warn | Error: connect ETIMEDOUT 192.168.4.248:80
mystrom.0 | 2021-08-20 10:00:54.681 | warn | http://192.168.4.248/report
mystrom.0 | 2021-08-20 10:00:54.680 | warn | Error: connect ETIMEDOUT 192.168.4.248:80
mystrom.0 | 2021-08-20 10:00:54.680 | warn | http://192.168.4.248/temp
mystrom.0 | 2021-08-20 10:00:54.680 | warn | Error: connect ETIMEDOUT 192.168.4.248:80
mystrom.0 | 2021-08-20 10:00:54.680 | warn | http://192.168.4.248/api/v1/settings
mystrom.0 | 2021-08-20 10:00:54.680 | warn | Error: connect ETIMEDOUT 192.168.4.248:80
mystrom.0 | 2021-08-20 10:00:54.680 | warn | http://192.168.4.248/report
mystrom.0 | 2021-08-20 10:00:54.680 | warn | Error: connect ETIMEDOUT 192.168.4.248:80
mystrom.0 | 2021-08-20 10:00:54.679 | warn | http://192.168.4.248/temp
`

**Comment by m3gg3** [comment]
die vielen fehlermeldungen und die tatsache das sich der adapter nicht inplace updaten lässt hindert mich an der installation, leider

**Comment by m3gg3** [comment]
> Ist das auch bei der github version so?

gibt es denn auch eine nicht github version?

**Comment by KayThe95** [comment]
Ich habe leider genau das gleiche Problem.

**Comment by TA2k** [comment]
Bitte mit 0.0.6 checken

**Comment by jhartlep** [comment]
Ich sehe bei mir jetzt auch keine WARN Meldungen mehr im Log.

**Comment by KayThe95** [comment]
<html>
<body>


host.raspberrypi | 2021-09-07 23:20:18.915 | error | instance system.adapter.mystrom.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --
mystrom.0 | 2021-09-07 23:20:18.325 | error | The state contains the forbidden properties meterCValue, appVersion, dns2, dns1, localSingleURL, localTouchUrl, isBridge, heartbeatPeriod, mac, serverPassword, localDoubleUrl, reportPeriod, wlanRssi, serverSsl, ipv4, wlanSsid, kernelVersion, meterType, serverUrl, localLongUrl, hardwareVersion, gateway, dhcpEnabled!
mystrom.0 | 2021-09-07 23:20:18.325 | error | Error: The state contains the forbidden properties meterCValue, appVersion, dns2, dns1, localSingleURL, localTouchUrl, isBridge, heartbeatPeriod, mac, serverPassword, localDoubleUrl, reportPeriod, wlanRssi, serverSsl, ipv4, wlanSsid, kernelVersion, meterType, serverUrl, localLongUrl, hardwareVersion, gateway, dhcpEnabled! at validateSetStateObjectArgument (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:6004:23) at Mystrom.setState (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:6091:21) at /opt/iobroker/node_modules/iobroker.mystrom/main.js:234:30
mystrom.0 | 2021-09-07 23:20:18.324 | error | unhandled promise rejection: The state contains the forbidden properties meterCValue, appVersion, dns2, dns1, localSingleURL, localTouchUrl, isBridge, heartbeatPeriod, mac, serverPassword, localDoubleUrl, reportPeriod, wlanRssi, serverSsl, ipv4, wlanSsid, kernelVersion, meterType, serverUrl, localLongUrl, hardwareVersion, gateway, dhcpEnabled!
mystrom.0 | 2021-09-07 23:20:18.323 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().


</body>
</html>

**Comment by JackDaniel007** [comment]
bekomme diese fehler:

mystrom.0 | 2021-09-08 12:25:26.367 | error | 3C71BFA85B34.cloudSettings.settings: [object Object]
mystrom.0 | 2021-09-08 12:25:26.367 | error | Error: The state contains the forbidden properties meterCValue, appVersion, dns2, dns1, localSingleURL, localTouchUrl, isBridge, heartbeatPeriod, mac, serverPassword, localDoubleUrl, reportPeriod, wlanRssi, serverSsl, ipv4, wlanSsid, kernelVersion, meterType, serverUrl, localLongUrl, hardwareVersion, gateway, dhcpEnabled!
mystrom.0 | 2021-09-08 12:25:26.289 | error | 3C71BFA852D0.cloudSettings.settings: [object Object]
mystrom.0 | 2021-09-08 12:25:26.289 | error | Error: The state contains the forbidden properties meterCValue, appVersion, dns2, dns1, localSingleURL, localTouchUrl, isBridge, heartbeatPeriod, mac, serverPassword, localDoubleUrl, reportPeriod, wlanRssi, serverSsl, ipv4, wlanSsid, kernelVersion, meterType, serverUrl, localLongUrl, hardwareVersion, gateway, dhcpEnabled!
mystrom.0 | 2021-09-08 12:25:26.125 | error | 3C71BFA85B34.cloudStatus.room: [object Object]
mystrom.0 | 2021-09-08 12:25:26.124 | error | Error: The state contains the forbidden properties id, name, type, color!
mystrom.0 | 2021-09-08 12:25:26.123 | error | 3C71BFA85B34.cloudStatus.energyReport: [object Object]
mystrom.0 | 2021-09-08 12:25:26.122 | error | Error: The state contains the forbidden properties allCost!
mystrom.0 | 2021-09-08 12:25:26.121 | error | 3C71BFA85B34.cloudStatus.schedule: [object Object]
mystrom.0 | 2021-09-08 12:25:26.120 | error | Error: The state contains the forbidden properties enabled, ranges!
mystrom.0 | 2021-09-08 12:25:26.116 | error | 3C71BFA852D0.cloudStatus.room: [object Object]
mystrom.0 | 2021-09-08 12:25:26.116 | error | Error: The state contains the forbidden properties id, name, type, color!
mystrom.0 | 2021-09-08 12:25:26.115 | error | 3C71BFA852D0.cloudStatus.energyReport: [object Object]
mystrom.0 | 2021-09-08 12:25:26.115 | error | Error: The state contains the forbidden properties allCost!
mystrom.0` | 2021-09-08 12:25:26.114 | error | 3C71BFA852D0.cloudStatus.schedule: [object Object]
mystrom.0 | 2021-09-08 12:25:26.113 | error | Error: The state contains the forbidden properties enabled, ranges!``

**Comment by TA2k** [comment]
Bitte nochmal via github installieren und testen

**Comment by KayThe95** [comment]
Habe es per Github nochmal geupdated. Diese Meldungen kommen nun noch, aber der Adapter stürzt zumindest nicht mehr ab.

<html>
<body>


mystrom.0 | 2021-09-08 13:11:36.691 | error | F008D1DD1454.cloudSettings.settings:
-- | -- | -- | --
mystrom.0 | 2021-09-08 13:11:36.690 | error | Error: The state contains the forbidden properties meterCValue, appVersion, dns2, dns1, localSingleURL, localTouchUrl, isBridge, heartbeatPeriod, mac, serverPassword, localDoubleUrl, reportPeriod, wlanRssi, serverSsl, ipv4, wlanSsid, kernelVersion, meterType, serverUrl, localLongUrl, hardwareVersion, gateway, dhcpEnabled!
mystrom.0 | 2021-09-08 13:11:36.519 | error | F008D1DD1454.cloudStatus.room:
mystrom.0 | 2021-09-08 13:11:36.519 | error | Error: The state contains the forbidden properties id, name, type, color!
mystrom.0 | 2021-09-08 13:11:36.518 | error | F008D1DD1454.cloudStatus.energyReport:
mystrom.0 | 2021-09-08 13:11:36.517 | error | Error: The state contains the forbidden properties allCost!
mystrom.0 | 2021-09-08 13:11:36.516 | error | F008D1DD1454.cloudStatus.schedule:
mystrom.0 | 2021-09-08 13:11:36.515 | error | Error: The state contains the forbidden properties enabled, ranges!


</body>
</html>

**Comment by TA2k** [comment]
kannst du nochmal installieren und ein error posten

**Comment by JackDaniel007** [comment]
hier mal meine errors mit der 0.8er version:

mystrom.0 | 2021-09-08 16:20:50.756 | error | 3C71BFA85B34.cloudSettings.settings: [object Object]
-- | -- | -- | --
mystrom.0 | 2021-09-08 16:20:50.755 | error | Error: The state contains the forbidden properties meterCValue, appVersion, dns2, dns1, localSingleURL, localTouchUrl, isBridge, heartbeatPeriod, mac, serverPassword, localDoubleUrl, reportPeriod, wlanRssi, serverSsl, ipv4, wlanSsid, kernelVersion, meterType, serverUrl, localLongUrl, hardwareVersion, gateway, dhcpEnabled!
mystrom.0 | 2021-09-08 16:20:50.680 | error | 3C71BFA852D0.cloudSettings.settings: [object Object]
mystrom.0 | 2021-09-08 16:20:50.679 | error | Error: The state contains the forbidden properties meterCValue, appVersion, dns2, dns1, localSingleURL, localTouchUrl, isBridge, heartbeatPeriod, mac, serverPassword, localDoubleUrl, reportPeriod, wlanRssi, serverSsl, ipv4, wlanSsid, kernelVersion, meterType, serverUrl, localLongUrl, hardwareVersion, gateway, dhcpEnabled!
mystrom.0 | 2021-09-08 16:20:50.503 | error | 3C71BFA85B34.cloudStatus.room: [object Object]
mystrom.0 | 2021-09-08 16:20:50.503 | error | Error: The state contains the forbidden properties id, name, type, color!
mystrom.0 | 2021-09-08 16:20:50.502 | error | 3C71BFA85B34.cloudStatus.energyReport: [object Object]
mystrom.0 | 2021-09-08 16:20:50.502 | error | Error: The state contains the forbidden properties allCost!
mystrom.0 | 2021-09-08 16:20:50.502 | error | 3C71BFA85B34.cloudStatus.schedule: [object Object]
mystrom.0 | 2021-09-08 16:20:50.501 | error | Error: The state contains the forbidden properties enabled, ranges!
mystrom.0 | 2021-09-08 16:20:50.498 | error | 3C71BFA852D0.cloudStatus.room: [object Object]
mystrom.0 | 2021-09-08 16:20:50.498 | error | Error: The state contains the forbidden properties id, name, type, color!
mystrom.0 | 2021-09-08 16:20:50.497 | error | 3C71BFA852D0.cloudStatus.energyReport: [object Object]
mystrom.0 | 2021-09-08 16:20:50.497 | error | Error: The state contains the forbidden properties allCost!
mystrom.0 | 2021-09-08 16:20:50.497 | error | 3C71BFA852D0.cloudStatus.schedule: [object Object]
mystrom.0 | 2021-09-08 16:20:50.496 | error | Error: The state contains the forbidden properties enabled, ranges!

**Comment by TA2k** [comment]
@JackDaniel007  bitte nochmal installieren

**Comment by JackDaniel007** [comment]
hab ich nun gemacht, hat sich aber nicht viel geändert

mystrom.0 | 2021-09-08 16:34:20.932 | error | {"meterCValue":"","appVersion":"3.82.60","dns2":"92.63.212.161","dns1":"192.168.1.72","localSingleURL":"","localTouchUrl":"","isBridge":"false","heartbeatPeriod":"60","mac":"3C71BFA85B34","serverPassword":"","localDoubleUrl":"","reportPeriod":"30","wlanRssi":"34","serverSsl":"true","ipv4":"192.168.1.61","wlanSsid":"JackDaniel","kernelVersion":"3.2.3","meterType":"","serverUrl":"device.mystrom.ch:443","localLongUrl":"","hardwareVersion":"1.0.0","gateway":"192.168.1.1","dhcpEnabled":"true"}
-- | -- | -- | --
mystrom.0 | 2021-09-08 16:34:20.931 | error | 3C71BFA85B34.cloudSettings.settings:
mystrom.0 | 2021-09-08 16:34:20.930 | error | Error: The state contains the forbidden properties meterCValue, appVersion, dns2, dns1, localSingleURL, localTouchUrl, isBridge, heartbeatPeriod, mac, serverPassword, localDoubleUrl, reportPeriod, wlanRssi, serverSsl, ipv4, wlanSsid, kernelVersion, meterType, serverUrl, localLongUrl, hardwareVersion, gateway, dhcpEnabled!
mystrom.0 | 2021-09-08 16:34:20.871 | error | {"meterCValue":"","appVersion":"3.82.60","dns2":"92.63.212.161","dns1":"192.168.1.72","localSingleURL":"","localTouchUrl":"","isBridge":"false","heartbeatPeriod":"60","mac":"3C71BFA852D0","serverPassword":"","localDoubleUrl":"","reportPeriod":"30","wlanRssi":"100","serverSsl":"true","ipv4":"192.168.1.64","wlanSsid":"JackDaniel","kernelVersion":"3.2.3","meterType":"","serverUrl":"device.mystrom.ch:443","localLongUrl":"","hardwareVersion":"1.0.0","gateway":"192.168.1.1","dhcpEnabled":"true"}
mystrom.0 | 2021-09-08 16:34:20.870 | error | 3C71BFA852D0.cloudSettings.settings:
mystrom.0 | 2021-09-08 16:34:20.870 | error | Error: The state contains the forbidden properties meterCValue, appVersion, dns2, dns1, localSingleURL, localTouchUrl, isBridge, heartbeatPeriod, mac, serverPassword, localDoubleUrl, reportPeriod, wlanRssi, serverSsl, ipv4, wlanSsid, kernelVersion, meterType, serverUrl, localLongUrl, hardwareVersion, gateway, dhcpEnabled!
mystrom.0 | 2021-09-08 16:34:20.656 | error | {"id":"sbiNPFCl5lEEXZ2P","name":"Balkon","type":"default","color":"#a1cbe1"}
mystrom.0 | 2021-09-08 16:34:20.656 | error | 3C71BFA85B34.cloudStatus.room:
mystrom.0 | 2021-09-08 16:34:20.656 | error | Error: The state contains the forbidden properties id, name, type, color!
mystrom.0 | 2021-09-08 16:34:20.655 | error | {"allCost":"1.58 EUR"}
mystrom.0 | 2021-09-08 16:34:20.655 | error | 3C71BFA85B34.cloudStatus.energyReport:
mystrom.0 | 2021-09-08 16:34:20.655 | error | Error: The state contains the forbidden properties allCost!
mystrom.0 | 2021-09-08 16:34:20.655 | error | {"enabled":false,"ranges":""}
mystrom.0 | 2021-09-08 16:34:20.654 | error | 3C71BFA85B34.cloudStatus.schedule:
mystrom.0 | 2021-09-08 16:34:20.654 | error | Error: The state contains the forbidden properties enabled, ranges!
mystrom.0 | 2021-09-08 16:34:20.650 | error | {"id":"Dc8LsQet5jN5qu2f","name":"Essbereich","type":"dining","color":"#a1cbe1"}
mystrom.0 | 2021-09-08 16:34:20.649 | error | 3C71BFA852D0.cloudStatus.room:
mystrom.0 | 2021-09-08 16:34:20.649 | error | Error: The state contains the forbidden properties id, name, type, color!
mystrom.0 | 2021-09-08 16:34:20.648 | error | {"allCost":"20.02 EUR"}
mystrom.0 | 2021-09-08 16:34:20.648 | error | 3C71BFA852D0.cloudStatus.energyReport:
mystrom.0 | 2021-09-08 16:34:20.648 | error | Error: The state contains the forbidden properties allCost!
mystrom.0 | 2021-09-08 16:34:20.648 | error | {"enabled":false,"ranges":""}
mystrom.0 | 2021-09-08 16:34:20.647 | error | 3C71BFA852D0.cloudStatus.schedule:
mystrom.0 | 2021-09-08 16:34:20.647 | error | Error: The state contains the forbidden properties enabled, ranges!
mystrom.0 | 2021-09-08 16:34:19.895 | info | starting. Version 0.0.8 in /opt/iobroker/node_modules/iobroker.mystrom, node: v12.22.5, js-controller: 3.3.15
mystrom.0 | 2021-09-08 16:34:16.045 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
mystrom.0 | 2021-09-08 16:34:16.044 | info | cleaned everything up...
mystrom.0 | 2021-09-08 16:34:16.044 | info | terminating
mystrom.0 | 2021-09-08 16:34:16.043 | info | Got terminate signal TERMINATE_YOURSELF

**Comment by TA2k** [comment]
nochmal testen bitte

**Comment by KayThe95** [comment]
Nun wird wieder leider der Log wieder mit Timeouts vollgespamt

**Comment by JackDaniel007** [comment]
bei mir startet nun der adapter ohne fehlermeldungen :)
leider funktioniert das ein/aus schalten unter localcommands nicht bei meinen steckdosen, simple api ist aktiviert da ich diese auch für die vis nutze

**Comment by m3gg3** [comment]
Wann wird der Adapter endlich so laufen wie er soll anstatt das Log zu fluten und in meinem Fall vor längerer Zeit den ganzen Raspberry Pi lahmzulegen?

**Comment by TA2k** [comment]
@JackDaniel007 Wenn kein Fehler kommt dann muss es am simpleAPI liegen. Welchen http pfad hast du denn wo gesetzt

**Comment by JackDaniel007** [comment]
hmm gar keinen, dachte das geht über die opjekte unter local commands
ich warte dann bis es auch über die opjekte vom adapter out of the box funktioniert, hab ja den mystrom-wifi-switch am laufen mit dem es funktioniert ;)
leider wird auch bei deinem kein gesamtverbrauch angezeigt, das war der grund warum ich diesen hier getestet habe.

**Comment by TA2k** [comment]
Es ist in der readme eigentlich gut erklärt.
Es wird nicht anders gehen weil mystrom es so vorsieht das man ein http link für jede aktion hinterlegen muss

**Comment by JackDaniel007** [comment]
muss es aber doch, bei diesem adapter [hier](https://github.com/rgwch/ioBroker.mystrom-wifi-switch) muss ich nur die ip eingeben, und es funktioniert

**Comment by TA2k** [comment]
Ich habe mal reingeschaut es passiert das gleiche. Du kannst nochmal neu installieren und protokollstufe auf debug setzen und und dann switch auf true oder false setzen im debug müsste dann sehen was ausgeführt wird

**Comment by JackDaniel007** [comment]
hier kommt nur 
mystrom.0 | 2021-09-09 16:35:33.592 | debug | ""

**Comment by TA2k** [comment]
Wie setzt du denn den Wert True? 
<img width="335" alt="image" src="https://user-images.githubusercontent.com/1307684/132713676-778ca198-15d3-4e8e-b10c-6cd09f40e4cb.png">

**Comment by JackDaniel007** [comment]
genau so wie auf dem screenshot zu sehen, macht auch keinen unterschied ob mit oder ohne bestätigt

**Comment by TA2k** [comment]
mystrom.0.F00XXXXXX.localCommands.switch setzt du auf True eigenartig kann ich nicht nachvollziehen.

**Comment by JackDaniel007** [comment]
hmm heute auf 0.11 aktualisiert und siehe da es läuft :)
was jetzt noch spannend wäre, ist der gesamtverbrauch für die vis ;)

**Comment by TA2k** [comment]
Wird denn sowas in der App angezeigt

**Comment by KayThe95** [comment]
Leider habe ich wieder die Timeouts drin. Eventuell liegt es aber auch an mir, ist echt seltsam.
Eine andere Frage hätte ich auch noch, wo kann ich die besagte URL (für das Schalten) in der App eingeben? Ich finde da überhaupt garkeine Option.

**Comment by TA2k** [comment]
Welche art von timeouts

**Comment by jhartlep** [comment]
Diese hier:

<html>
<body>


mystrom.0 | 12899 | 2021-09-11 12:48:59.497 | warn | Error: connect ETIMEDOUT 192.168.4.248:80
-- | -- | -- | -- | --
mystrom.0 | 12899 | 2021-09-11 12:48:59.497 | warn | http://192.168.4.248/api/v1/settings
mystrom.0 | 12899 | 2021-09-11 12:48:59.497 | warn | Error: connect ETIMEDOUT 192.168.4.248:80
mystrom.0 | 12899 | 2021-09-11 12:48:59.497 | warn | http://192.168.4.248/report
mystrom.0 | 12899 | 2021-09-11 12:48:59.497 | warn | Error: connect ETIMEDOUT 192.168.4.248:80
mystrom.0 | 12899 | 2021-09-11 12:48:59.497 | warn | http://192.168.4.248/temp
mystrom.0 | 12899 | 2021-09-11 12:48:59.497 | warn | Error: connect ETIMEDOUT 192.168.4.248:80
mystrom.0 | 12899 | 2021-09-11 12:48:59.497 | warn | http://192.168.4.248/api/v1/settings
mystrom.0 | 12899 | 2021-09-11 12:48:59.497 | warn | Error: connect ETIMEDOUT 192.168.4.248:80
mystrom.0 | 12899 | 2021-09-11 12:48:59.497 | warn | http://192.168.4.248/report
mystrom.0 | 12899 | 2021-09-11 12:48:59.497 | warn | Error: connect ETIMEDOUT 192.168.4.248:80
mystrom.0 | 12899 | 2021-09-11 12:48:59.497 | warn | http://192.168.4.248/temp
mystrom.0 | 12899 | 2021-09-11 12:48:59.497 | warn | Error: connect ETIMEDOUT 192.168.4.248:80
mystrom.0 | 12899 | 2021-09-11 12:48:59.497 | warn | http://192.168.4.248/report
mystrom.0 | 12899 | 2021-09-11 12:48:59.497 | warn | Error: connect ETIMEDOUT 192.168.4.248:80
mystrom.0 | 12899 | 2021-09-11 12:48:59.497 | warn | http://192.168.4.248/temp


</body>
</html>

Bei mir ist die Schaltdose im übrigen im "Solarmodus"; dort hängen zwei Solar panele dran.

**Comment by TA2k** [comment]
in 0.0.12 werden die Fehler ignoriert

**Comment by KayThe95** [comment]
Über Github lässt sich der Adapter irgendwie nicht auf 0.0.12 updaten, er bleibt in der Instanzübersicht auf 0.0.11

**Comment by TA2k** [comment]
Sollte jetzt gehen

**Comment by m3gg3** [comment]
Der schlimmste Adapter ever. Hände weg wenn ihr das log nicht voll haben wollt und das seit 6 Versionen und es wird immer schlimmer
