### ISSUE TITLE
Error Log-Warnmeldungen wieder da

### ISSUE THREAD

**Issue by KayThe95** [TA2k/ioBroker.mystrom#72]
Der Log wird wieder geflutet mit Timeouts. War ein paar Tage nach Update auf 0.12 wieder gut aber es fängt nun wieder an.

<html>
<body>

mystrom.0 | 2021-09-20 22:20:54.930 | warn | Error: connect EPIPE 192.168.178.104:80
-- | -- | -- | --
mystrom.0 | 2021-09-20 22:20:54.930 | warn | http://192.168.178.104/report
mystrom.0 | 2021-09-20 22:20:54.929 | warn | Error: connect EPIPE 192.168.178.104:80
mystrom.0 | 2021-09-20 22:20:54.929 | warn | http://192.168.178.104/api/v1/settings
mystrom.0 | 2021-09-20 22:20:54.929 | warn | Error: connect EPIPE 192.168.178.104:80
mystrom.0 | 2021-09-20 22:20:54.928 | warn | http://192.168.178.104/temp
mystrom.0 | 2021-09-20 22:20:54.928 | warn | Error: connect EPIPE 192.168.178.104:80
mystrom.0 | 2021-09-20 22:20:54.928 | warn | http://192.168.178.104/temp
mystrom.0 | 2021-09-20 22:20:54.927 | warn | Error: connect EPIPE 192.168.178.104:80
mystrom.0 | 2021-09-20 22:20:54.927 | warn | http://192.168.178.104/report
mystrom.0 | 2021-09-20 22:20:54.927 | warn | Error: connect EPIPE 192.168.178.104:80

</body>
</html>

**Comment by TA2k** [comment]
Ich habe das ingorieren von epipe fehler mit aufgenommen
